name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# TODO: add jobs that test on different host platforms (windows, aarch64, etc)
# TODO: build examples with btest on CI
#   Some of them are interactive so there should be some way to just build things without running them

jobs:
  btest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup toolchain install stable --no-self-update --profile minimal

      - name: Install/Restore Dependency Cache
        id: cache-deps
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: clang make fasm mingw-w64 wine64 gcc-aarch64-linux-gnu qemu-user
          version: 1.0 # version of the cache

      - name: Install uxncli
        run: |
          git clone https://git.sr.ht/~rabbits/uxn11
          cd uxn11
          make cli

      - name: Run Tests
        run: |
          make -B
          PATH=$(realpath uxn11/bin):$PATH ./build/btest
