name: CI
on: [push, pull_request]

# TODO: add jobs that test on different host platforms (windows, aarch64, etc)
# TODO: build examples on CI
#   May require a special support for build-only mode in btest

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: rustup toolchain install stable --no-self-update --profile minimal
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq -y build-essential clang make fasm mingw-w64 wine64 gcc-aarch64-linux-gnu qemu-user xxd cmake libpng-dev binutils-sh-elf python3 libusb-1.0-0-dev libsdl2-dev gcc-sh4-linux-gnu
          sh4-linux-gnu-gcc -v
          git clone https://git.planet-casio.com/Lephenixnoir/fxsdk
          cd fxsdk
          mkdir fxusr
          cmake -B build -DCMAKE_INSTALL_PREFIX=fxusr -DFXLINK_DISABLE_UDISKS2=1
          make -C build
          make -C build install
          cd ..

          git clone https://git.sr.ht/~rabbits/uxn11
          cd uxn11
          make
      - name: Build Toolchain
        run: |
          make -B
      - name: Run Tests
        run: |
          PREFIX=sh4-linux-gnu PATH=$(realpath uxn11/bin):$(realpath fxsdk/fxusr/bin):$PATH ./build/btest -xt gas-aarch64-darwin
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: rustup toolchain install stable --no-self-update --profile minimal
      - name: Build Toolchain
        run: make -B
      - name: Run Tests
        run: ./build/btest -t gas-aarch64-darwin
