name: 🧪 Test

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]

jobs:
  test_linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install Clang and fasm
        run: |
          sudo apt-get update
          sudo apt-get install -y clang make fasm
      - name: Run Linux tests
        run: make test

  test_mingw_on_linux:
    name: Test MinGW (cross-compiled) on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang make fasm mingw-w64 wine64
      - name: Run MinGW tests
        run: make test-mingw32
